### ISSUE TITLE
Implement tool calling for ChatBedrock

### ISSUE THREAD

**Issue by eugeneduvenage** [langchain-ai/langchain-aws#22]
Currently ChatBedrock cannot easily be used for tool calling when using langchain agents as it does not implement the bind_tools method. An example would be this langchain example using Anthropic: https://python.langchain.com/docs/use_cases/tool_use/agents/ and the create_tool_calling_agent function.

Are there any plans to support this common use case, at least when using Bedrock Anthropic models? 
It might also be nice to add the BedrockChat to the langchain integrations page here: https://python.langchain.com/docs/integrations/chat/ so that the supported features can easily be understood.

**Comment by eugeneduvenage** [comment]
I had a look at implementing a ChatBedrockAnthropic Chat model and while its not too complex to add the bind_tools method that adds a tools section to the request using the Anthropic messages API, which requires adding a header to enable the feature. However I was not able to get the boto3 bedrock client to stop trying to validate the request parameters and complain about the new tools field. I set parameter_validation to false in the boto config with no improvement. 
Details of the tools format in the Anthropic messages API can be found here: https://docs.anthropic.com/claude/docs/tool-use.

I was able to get tool calling working using this example code: https://github.com/aws-samples/amazon-bedrock-workshop/blob/a390ae3231e4c1fcd88e698d3f8bc6def01c43f0/10_FunctionCalling/bedrock_boto3_function_calling_claude2.ipynb, but it does not use the native Anthropic capabilities.

**Comment by bigbernnn** [comment]
This is the [PR](https://github.com/langchain-ai/langchain-aws/pull/37). Right now, it is only supporting Anthropic models.

**Comment by ssg-kstewart** [comment]
Appreciate the work you've done here. With regard to "tool_calls" being populated, I am indeed now seeing expected formatting. However, I have an implementation mimicking the documentation for LangGraph [collaborative multi-agent system](https://langchain-ai.github.io/langgraph/tutorials/multi_agent/multi-agent-collaboration/) and seeing odd behavior when using ChatBedrock over ChatOpenAI. In my case, in addition to the entry point node not calling the correct tool, tools are not actually being called at all and I'm having difficulty discerning the root cause. On top of this, I'm getting a "list index out of range"  here:

```
File "/usr/local/lib/python3.11/site-packages/langchain_aws/llms/bedrock.py", line 235, in prepare_output
   text = content[0].get("text")
            ~~~~~~~^^^
IndexError: list index out of range
```

I have verified that simply swapping to the ChatOpenAI model resolves the issue and tool calling works as expected.

**If this requires a standalone issue, please let me know and I will get that sorted.**

**Comment by 3coins** [comment]
@eugeneduvenage 
Tool support has been added both in ChatBedrockConverse and ChatBedrock classes, can you try again and let us know if you come across any issue.

**Comment by eugeneduvenage** [comment]
Thanks! Confirmed it is working for me using ChatBedrock.

**Comment by BradAxl** [comment]
Hi @eugeneduvenage 
can you provide an example of how you're using ChatBedrock or ChatBedrockConverse for tool calling please? 
Thanks in advance

**Comment by wondamo** [comment]
> Thanks! Confirmed it is working for me using ChatBedrock.

It's not working for me, can you provide an example of how you're usingit
