### ISSUE TITLE
Suport for Cohere Command-R and Command-R+

### ISSUE THREAD

**Issue by ksaegusa** [langchain-ai/langchain-aws#238]
I was wondering if it would be possible to add support for the Cohere Command-R model in ChatBedrock. I think this feature would really enhance the platform and be helpful for users. 

We would appreciate your consideration.

**Comment by ksaegusa** [comment]
@3coins 
Thank you for your comment!
I can confirm that the Command-R+ model works for `invoke` and `stream` in　ChatBedrockConverse.

However, when trying to use ChatHistory with Command-R+, it seems necessary to specify a HumanMessage at the beginning, otherwise an error occurs.
(This issue did not occur with the Anthropic model, so I believe it is a problem specific to the Command-R model.)
```sh
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the Converse operation: A conversation must start with a user message. Try again with a conversation that starts with a user message.
```

NG:
```py
chat_template = ChatPromptTemplate.from_messages(
    [
        SystemMessage(
            content=(
                "あなたは日本語が得意なボブです"
                "質問に答えてください"
            )
        ),
        AIMessage(
            content=(
                "ボブです。どうぞよろしくお願いします。何かお手伝いできることはありま"
            )
        ),
        HumanMessagePromptTemplate.from_template("{text}"),
    ]
)
```

SUCCESS:
```py
chat_template = ChatPromptTemplate.from_messages(
    [
        HumanMessage(
            content=(
                "あなたは日本語が得意なボブです"
                "質問に答えてください"
            )
        ),
        AIMessage(
            content=(
                "ボブです。どうぞよろしくお願いします。何かお手伝いできることはありま"
            )
        ),
        HumanMessagePromptTemplate.from_template("{text}"),
    ]
)
```

**Comment by 3coins** [comment]
@ksaegusa 
It seems like the Human message is expected order before an AI message in requests to Bedrock. I tested your example with Anthropic haiku model, and received the same error. It also seems like you are trying to manage the chat history in the prompt template rather than using the `RunnableWithHistoryMessage` object. I would recommend looking at this guide to setup the chat history, you can adapt the code by adding the `system` and `human` message only in the prompt template. Can you try that and let me know if that helps.
https://python.langchain.com/v0.2/docs/how_to/message_history/

**Note**: If you are planning to use LangGraph in the near future, see the v0.3 guide which recommends using the LangGraph memory for the history. https://python.langchain.com/docs/how_to/message_history/

**Comment by ksaegusa** [comment]
@3coins 
Thank you!
It turns out the issue was with the AI message. 
After trying `RunnableWithHistoryMessage`, the problem was resolved.

Also, thank you for the information about `LangGraph`. I am considering using it in the future and will check it out!

**Comment by 3coins** [comment]
Closing, as Cohere models are supported in v0.2.3.
